services:
  amiticia-site:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '0.5'
          memory: 250MB     
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.amiticia.rule=Host(`amiticia.cc`)"
      - "traefik.docker.network=network_public"      
      - "traefik.http.routers.amiticia.entrypoints=websecure"
      - "traefik.http.routers.amiticia.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.amiticia.service=amiticia"
      - "traefik.http.services.amiticia.loadbalancer.server.port=3000"

networks:
  network_public:
  external: true